# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: William Tulloch
email: me@williamtulloch.com
description: "The blog of william tulloch"
subheader: "Adventures in code"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wtulloch.github.io" # the base hostname & protocol for your site
twitter_username: wtulloch
github_username:  wtulloch

# Build settings
markdown: kramdown
